sonar.projectKey=student-analytics-api
sonar.projectName=Student Analytics API
sonar.projectVersion=1.0.0
sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.bandit.reportPaths=bandit-report.json
sonar.qualitygate.wait=true
sonar.host.url=http://localhost:9000
sonar.token=your-sonar-token